version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-escola
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escola
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno123
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: escola-api
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - "8080:8080"
